dataset:
  # Paths for dataset-related files and directories
  original_dir: "dataset/original_sequences"
  manipulated_dir: "dataset/manipulated_sequences"
  labels_csv: "data/labels.csv"
  frames_dir: "data/frames"
  ppg_cells_dir: "data/ppg_cells"

preprocessing:
  # Frame extraction and signal processing parameters
  frame_skip: 10  # Extract a frame every 10 frames
  window_size: 64  # Size of sliding window for PPG extraction
  start_index: 0  # Optional: start index for subset processing
  end_index: 500   # Optional: end index for subset processing

model:
  # Model training and saving parameters
  num_classes: 2  # Binary classification (real vs fake)
  save_path: "models/deepfake_detector.h5"

results:
  # Reporting and evaluation parameters
  report_path: "results/model_evaluation_report.txt"