# Dataset paths
dataset:
  root: dataset
  labels_csv: data/labels.csv
  frames_dir: data/frames
  ppg_cells_dir: data/ppg_cells

# Preprocessing parameters
preprocessing:
  frame_skip: 2  # Reduce the number of frames extracted to speed up preprocessing
  start_index: 0  # Starting index for video range
  end_index: 500  # Process 500 videos for training and testing

# Model parameters
model:
  num_classes: 2  # Binary classification: real (0) vs fake (1)
  save_path: results/models/resnet_classifier.pth

# Training parameters
training:
  batch_size: 8  # Smaller batch size for better GPU utilization on small datasets
  epochs: 50  # Lower epochs to balance training time with accuracy
  learning_rate: 0.00001  # A slightly higher learning rate to speed up convergence
  split_ratio: 0.85  # Use 85% for training and 15% for testing

# Evaluation parameters
evaluation:
  batch_size: 8  # Match training batch size for consistency
